[project]
name = "job-jumper"
version = "0.1.0"
description = "description"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.55.0",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.4",
]
